name: Build and Upload AppImage

on:
  push:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Build Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          push: false
          load: true
          tags: appimage-builder:latest
      - name: Extract AppImage from container
        run: |
          # Create a container from the image
          container_id=$(docker create appimage-builder:latest)
          # Copy the AppImage from the container to the host
          docker cp $container_id:/opt/ft_scservo/build/FT_SCServo-x86_64.AppImage ./
          # Clean up the container
          docker rm $container_id
      - name: Create release and upload artifacts
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          sudo apt-get update
          sudo apt-get install libfuse2
          wget -q https://github.com/TheAssassin/pyuploadtool/releases/download/continuous/pyuploadtool-x86_64.AppImage
          chmod +x pyuploadtool-x86_64.AppImage
          ./pyuploadtool-x86_64.AppImage FT_SCServo-x86_64.AppImage
